// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Noto Sans Arabic (نوتو سنس عربی) — Noto Sans Arabic variable font (wght 100-900; width axis pinned to normal).
 *
 * Upstream: https://github.com/google/fonts (v2.012), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-noto-sans-arabic`.
 */
export const notoSansArabic = localFont({
  src: [
    { path: './NotoSansArabic-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  variable: '--font-noto-sans-arabic',
  display: 'swap',
})
