// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Cairo (قاهره) — Cairo variable font (wght 200-1000, plus a slant axis).
 *
 * Upstream: https://github.com/google/fonts (v3.130), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-cairo`.
 */
export const cairo = localFont({
  src: [
    { path: './Cairo-VF.woff2', weight: '200 1000', style: 'normal' },
  ],
  variable: '--font-cairo',
  display: 'swap',
})
