// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Mikhak (میخک) — Mikhak variable font (wght 100-900, plus DSTY and KSHD axes), Latin digits.
 *
 * Upstream: https://github.com/aminabedi68/Mikhak (v3.4), license: OFL-1.1.
 * CSS variable: `--font-mikhak`.
 */
export declare const mikhak: PersianFont
