// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
// Demo gallery only: the same font files as the package, but never preloaded.
import localFont from 'next/font/local'

export const vazirMatn = localFont({
  src: [
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-Thin.woff2', weight: '100', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-ExtraLight.woff2', weight: '200', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-Light.woff2', weight: '300', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-Bold.woff2', weight: '700', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-ExtraBold.woff2', weight: '800', style: 'normal' },
    { path: '../next-persian-fonts/vazirmatn/Vazirmatn-FD-Black.woff2', weight: '900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const vazirmatnRoundDots = localFont({
  src: [
    { path: '../next-persian-fonts/vazirmatn-round-dots/Vazirmatn-RD-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const sahel = localFont({
  src: [
    { path: '../next-persian-fonts/sahel/Sahel-VF.woff2', weight: '400 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const sahelFD = localFont({
  src: [
    { path: '../next-persian-fonts/sahel-fd/Sahel-Light-FD.woff2', weight: '300', style: 'normal' },
    { path: '../next-persian-fonts/sahel-fd/Sahel-FD.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/sahel-fd/Sahel-SemiBold-FD.woff2', weight: '600', style: 'normal' },
    { path: '../next-persian-fonts/sahel-fd/Sahel-Bold-FD.woff2', weight: '700', style: 'normal' },
    { path: '../next-persian-fonts/sahel-fd/Sahel-Black-FD.woff2', weight: '900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const estedad = localFont({
  src: [
    { path: '../next-persian-fonts/estedad/Estedad-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const estedadFD = localFont({
  src: [
    { path: '../next-persian-fonts/estedad/Estedad-FD-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const samim = localFont({
  src: [
    { path: '../next-persian-fonts/samim/Samim.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/samim/Samim-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/samim/Samim-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const samimFD = localFont({
  src: [
    { path: '../next-persian-fonts/samim-fd/Samim-FD.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/samim-fd/Samim-Medium-FD.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/samim-fd/Samim-Bold-FD.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const shabnam = localFont({
  src: [
    { path: '../next-persian-fonts/shabnam/Shabnam-Thin.woff2', weight: '100', style: 'normal' },
    { path: '../next-persian-fonts/shabnam/Shabnam-Light.woff2', weight: '300', style: 'normal' },
    { path: '../next-persian-fonts/shabnam/Shabnam.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/shabnam/Shabnam-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/shabnam/Shabnam-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const shabnamFD = localFont({
  src: [
    { path: '../next-persian-fonts/shabnam-fd/Shabnam-Thin-FD.woff2', weight: '100', style: 'normal' },
    { path: '../next-persian-fonts/shabnam-fd/Shabnam-Light-FD.woff2', weight: '300', style: 'normal' },
    { path: '../next-persian-fonts/shabnam-fd/Shabnam-FD.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/shabnam-fd/Shabnam-Medium-FD.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/shabnam-fd/Shabnam-Bold-FD.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const tanha = localFont({
  src: [
    { path: '../next-persian-fonts/tanha/Tanha.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const tanhaFD = localFont({
  src: [
    { path: '../next-persian-fonts/tanha-fd/Tanha-FD.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const parastoo = localFont({
  src: [
    { path: '../next-persian-fonts/parastoo/Parastoo.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/parastoo/Parastoo-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const parastooFD = localFont({
  src: [
    { path: '../next-persian-fonts/parastoo-fd/Parastoo-FD.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/parastoo-fd/Parastoo-Bold-FD.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const gandom = localFont({
  src: [
    { path: '../next-persian-fonts/gandom/Gandom.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const gandomFD = localFont({
  src: [
    { path: '../next-persian-fonts/gandom-fd/Gandom-FD.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const mikhak = localFont({
  src: [
    { path: '../next-persian-fonts/mikhak/Mikhak-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const mikhakFD = localFont({
  src: [
    { path: '../next-persian-fonts/mikhak-fd/Mikhak-FD-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const vazirCodeFD = localFont({
  src: [
    { path: '../next-persian-fonts/vazir-code-fd/Vazir-Code-FD.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const behdad = localFont({
  src: [
    { path: '../next-persian-fonts/behdad/Behdad-Regular.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const nika = localFont({
  src: [
    { path: '../next-persian-fonts/nika/Nika-Regular.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const lalezar = localFont({
  src: [
    { path: '../next-persian-fonts/lalezar/Lalezar-Regular.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const markaziText = localFont({
  src: [
    { path: '../next-persian-fonts/markazi-text/MarkaziText-VF.woff2', weight: '400 700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const mirza = localFont({
  src: [
    { path: '../next-persian-fonts/mirza/Mirza-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/mirza/Mirza-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/mirza/Mirza-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../next-persian-fonts/mirza/Mirza-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const reemKufi = localFont({
  src: [
    { path: '../next-persian-fonts/reem-kufi/ReemKufi-VF.woff2', weight: '400 700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const notoNaskhArabic = localFont({
  src: [
    { path: '../next-persian-fonts/noto-naskh-arabic/NotoNaskhArabic-VF.woff2', weight: '400 700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const notoSansArabic = localFont({
  src: [
    { path: '../next-persian-fonts/noto-sans-arabic/NotoSansArabic-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const notoKufiArabic = localFont({
  src: [
    { path: '../next-persian-fonts/noto-kufi-arabic/NotoKufiArabic-VF.woff2', weight: '100 900', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const notoNastaliqUrdu = localFont({
  src: [
    { path: '../next-persian-fonts/noto-nastaliq-urdu/NotoNastaliqUrdu-VF.woff2', weight: '400 700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const ibmPlexSansArabic = localFont({
  src: [
    { path: '../next-persian-fonts/ibm-plex-sans-arabic/IBMPlexSansArabic-Thin.woff2', weight: '100', style: 'normal' },
    { path: '../next-persian-fonts/ibm-plex-sans-arabic/IBMPlexSansArabic-ExtraLight.woff2', weight: '200', style: 'normal' },
    { path: '../next-persian-fonts/ibm-plex-sans-arabic/IBMPlexSansArabic-Light.woff2', weight: '300', style: 'normal' },
    { path: '../next-persian-fonts/ibm-plex-sans-arabic/IBMPlexSansArabic-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/ibm-plex-sans-arabic/IBMPlexSansArabic-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/ibm-plex-sans-arabic/IBMPlexSansArabic-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../next-persian-fonts/ibm-plex-sans-arabic/IBMPlexSansArabic-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const amiri = localFont({
  src: [
    { path: '../next-persian-fonts/amiri/Amiri-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/amiri/Amiri-Bold.woff2', weight: '700', style: 'normal' },
    { path: '../next-persian-fonts/amiri/Amiri-Italic.woff2', weight: '400', style: 'italic' },
    { path: '../next-persian-fonts/amiri/Amiri-BoldItalic.woff2', weight: '700', style: 'italic' },
  ],
  display: 'swap',
  preload: false,
})

export const harmattan = localFont({
  src: [
    { path: '../next-persian-fonts/harmattan/Harmattan-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/harmattan/Harmattan-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/harmattan/Harmattan-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../next-persian-fonts/harmattan/Harmattan-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const scheherazadeNew = localFont({
  src: [
    { path: '../next-persian-fonts/scheherazade-new/ScheherazadeNew-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/scheherazade-new/ScheherazadeNew-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/scheherazade-new/ScheherazadeNew-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../next-persian-fonts/scheherazade-new/ScheherazadeNew-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const lateef = localFont({
  src: [
    { path: '../next-persian-fonts/lateef/Lateef-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/lateef/Lateef-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../next-persian-fonts/lateef/Lateef-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../next-persian-fonts/lateef/Lateef-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const katibeh = localFont({
  src: [
    { path: '../next-persian-fonts/katibeh/Katibeh-Regular.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const arefRuqaa = localFont({
  src: [
    { path: '../next-persian-fonts/aref-ruqaa/ArefRuqaa-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../next-persian-fonts/aref-ruqaa/ArefRuqaa-Bold.woff2', weight: '700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const rubik = localFont({
  src: [
    { path: '../next-persian-fonts/rubik/Rubik-VF.woff2', weight: '300 900', style: 'normal' },
    { path: '../next-persian-fonts/rubik/Rubik-Italic-VF.woff2', weight: '300 900', style: 'italic' },
  ],
  display: 'swap',
  preload: false,
})

export const jomhuria = localFont({
  src: [
    { path: '../next-persian-fonts/jomhuria/Jomhuria-Regular.woff2', weight: '400', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const elMessiri = localFont({
  src: [
    { path: '../next-persian-fonts/el-messiri/ElMessiri-VF.woff2', weight: '400 700', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const changa = localFont({
  src: [
    { path: '../next-persian-fonts/changa/Changa-VF.woff2', weight: '200 800', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const balooBhaijaan2 = localFont({
  src: [
    { path: '../next-persian-fonts/baloo-bhaijaan-2/BalooBhaijaan2-VF.woff2', weight: '400 800', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})

export const cairo = localFont({
  src: [
    { path: '../next-persian-fonts/cairo/Cairo-VF.woff2', weight: '200 1000', style: 'normal' },
  ],
  display: 'swap',
  preload: false,
})
