// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Parastoo (پرستو) — Parastoo with Persian digits, 2 static weights (400, 700).
 *
 * Upstream: https://github.com/rastikerdar/parastoo-font (v2.0.1), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-parastoo-fd`.
 */
export const parastooFD = localFont({
  src: [
    { path: './Parastoo-FD.woff2', weight: '400', style: 'normal' },
    { path: './Parastoo-Bold-FD.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-parastoo-fd',
  display: 'swap',
})
