// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Shabnam (شبنم) — Shabnam, 5 static weights (100, 300, 400, 500, 700), Latin digits.
 *
 * Upstream: https://github.com/rastikerdar/shabnam-font (v5.0.1), license: OFL-1.1 (Arabic glyphs) + Bitstream Vera / Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-shabnam`.
 */
export declare const shabnam: PersianFont
