// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Shabnam (شبنم) — Shabnam, 5 static weights (100, 300, 400, 500, 700), Latin digits.
 *
 * Upstream: https://github.com/rastikerdar/shabnam-font (v5.0.1), license: OFL-1.1 (Arabic glyphs) + Bitstream Vera / Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-shabnam`.
 */
export const shabnam = localFont({
  src: [
    { path: './Shabnam-Thin.woff2', weight: '100', style: 'normal' },
    { path: './Shabnam-Light.woff2', weight: '300', style: 'normal' },
    { path: './Shabnam.woff2', weight: '400', style: 'normal' },
    { path: './Shabnam-Medium.woff2', weight: '500', style: 'normal' },
    { path: './Shabnam-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-shabnam',
  display: 'swap',
})
