// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Samim (صمیم) — Samim, 3 static weights (400, 500, 700), Latin digits.
 *
 * Upstream: https://github.com/rastikerdar/samim-font (v4.0.5), license: OFL-1.1 (Arabic glyphs) + Bitstream Vera / Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-samim`.
 */
export const samim = localFont({
  src: [
    { path: './Samim.woff2', weight: '400', style: 'normal' },
    { path: './Samim-Medium.woff2', weight: '500', style: 'normal' },
    { path: './Samim-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-samim',
  display: 'swap',
})
