// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Vazirmatn (وزیرمتن) — Vazirmatn variable font (wght 100-900) in a single file, Latin digits.
 *
 * Upstream: https://github.com/rastikerdar/vazirmatn (v33.003), license: OFL-1.1.
 * CSS variable: `--font-vazirmatn-variable`.
 */
export const vazirmatnVariable = localFont({
  src: [
    { path: './Vazirmatn[wght].woff2', weight: '100 900', style: 'normal' },
  ],
  variable: '--font-vazirmatn-variable',
  display: 'swap',
})
