// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Vazirmatn (وزیرمتن) — Vazirmatn variable font (wght 100-900) in a single file, Latin digits.
 *
 * Upstream: https://github.com/rastikerdar/vazirmatn (v33.003), license: OFL-1.1.
 * CSS variable: `--font-vazirmatn-variable`.
 */
export declare const vazirmatnVariable: PersianFont
