// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Gandom (گندم) — Gandom with Persian digits, single weight (400).
 *
 * Upstream: https://github.com/rastikerdar/gandom-font (v0.8), license: OFL-1.1 (Arabic glyphs) + Bitstream Vera / Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-gandom-fd`.
 */
export declare const gandomFD: PersianFont
