// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Behdad (بهداد) — Behdad, single weight (400). Arabic-script only (no Latin letters or Latin digits): pair it with a Latin font.
 *
 * Upstream: https://github.com/font-store/BehdadFont (v1.0.0), license: OFL-1.1.
 * CSS variable: `--font-behdad`.
 */
export const behdad = localFont({
  src: [
    { path: './Behdad-Regular.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-behdad',
  display: 'swap',
})
