// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Behdad (بهداد) — Behdad, single weight (400). Arabic-script only (no Latin letters or Latin digits): pair it with a Latin font.
 *
 * Upstream: https://github.com/font-store/BehdadFont (v1.0.0), license: OFL-1.1.
 * CSS variable: `--font-behdad`.
 */
export declare const behdad: PersianFont
