// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Scheherazade New (شهرزاد) — Scheherazade New Naskh font, 4 static weights (400, 500, 600, 700).
 *
 * Upstream: https://github.com/silnrsi/font-scheherazade (v4.500), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-scheherazade-new`.
 * Not preloaded (4 files); fonts load when first used. A variable export of the family preloads a single file.
 */
export declare const scheherazadeNew: PersianFont
