// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Scheherazade New (شهرزاد) — Scheherazade New Naskh font, 4 static weights (400, 500, 600, 700).
 *
 * Upstream: https://github.com/silnrsi/font-scheherazade (v4.500), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-scheherazade-new`.
 */
export const scheherazadeNew = localFont({
  src: [
    { path: './ScheherazadeNew-Regular.woff2', weight: '400', style: 'normal' },
    { path: './ScheherazadeNew-Medium.woff2', weight: '500', style: 'normal' },
    { path: './ScheherazadeNew-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: './ScheherazadeNew-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-scheherazade-new',
  display: 'swap',
})
