// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Harmattan (هرمتان) — Harmattan, 4 static weights (400, 500, 600, 700).
 *
 * Upstream: https://github.com/silnrsi/font-harmattan (v4.400), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-harmattan`.
 * Not preloaded (4 files); fonts load when first used. A variable export of the family preloads a single file.
 */
export const harmattan = localFont({
  src: [
    { path: './Harmattan-Regular.woff2', weight: '400', style: 'normal' },
    { path: './Harmattan-Medium.woff2', weight: '500', style: 'normal' },
    { path: './Harmattan-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: './Harmattan-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-harmattan',
  display: 'swap',
  preload: false,
})
