// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Harmattan (هرمتان) — Harmattan, 4 static weights (400, 500, 600, 700).
 *
 * Upstream: https://github.com/silnrsi/font-harmattan (v4.400), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-harmattan`.
 */
export declare const harmattan: PersianFont
