// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Mikhak (میخک) — Mikhak variable font with Persian digits (wght 100-900, plus DSTY and KSHD axes).
 *
 * Upstream: https://github.com/aminabedi68/Mikhak (v3.4), license: OFL-1.1.
 * CSS variable: `--font-mikhak-fd`.
 */
export declare const mikhakFD: PersianFont
