// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Aref Ruqaa (عارف رقعه) — Aref Ruqaa (Ruq'ah calligraphic style), 2 weights (400, 700).
 *
 * Upstream: https://github.com/google/fonts (v1.003), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-aref-ruqaa`.
 */
export declare const arefRuqaa: PersianFont
