// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Aref Ruqaa (عارف رقعه) — Aref Ruqaa (Ruq'ah calligraphic style), 2 weights (400, 700).
 *
 * Upstream: https://github.com/google/fonts (v1.003), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-aref-ruqaa`.
 */
export const arefRuqaa = localFont({
  src: [
    { path: './ArefRuqaa-Regular.woff2', weight: '400', style: 'normal' },
    { path: './ArefRuqaa-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-aref-ruqaa',
  display: 'swap',
})
