// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Vazir Code (وزیر کد) — Vazir Code monospace font, single weight (400), Latin digits.
 *
 * Upstream: https://github.com/rastikerdar/vazir-code-font (v1.1.2), license: Bitstream Vera License + Public Domain (changes).
 * CSS variable: `--font-vazir-code`.
 */
export const vazirCode = localFont({
  src: [
    { path: './Vazir-Code.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-vazir-code',
  display: 'swap',
})
