// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Noto Nastaliq Urdu (نوتو نستعلیق) — Noto Nastaliq Urdu variable font (wght 400-700). Nastaliq script; needs a generous line-height.
 *
 * Upstream: https://github.com/google/fonts (v3.009), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-noto-nastaliq-urdu`.
 */
export const notoNastaliqUrdu = localFont({
  src: [
    { path: './NotoNastaliqUrdu[wght].woff2', weight: '400 700', style: 'normal' },
  ],
  variable: '--font-noto-nastaliq-urdu',
  display: 'swap',
})
