// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Lateef (لطیف) — Lateef (Sindhi/Urdu-style Naskh), 4 static weights (400, 500, 600, 700).
 *
 * Upstream: https://github.com/silnrsi/font-lateef (v4.400), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-lateef`.
 * Not preloaded (4 files); fonts load when first used. A variable export of the family preloads a single file.
 */
export declare const lateef: PersianFont
