// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Noto Kufi Arabic (نوتو کوفی) — Noto Kufi Arabic variable font (wght 100-900).
 *
 * Upstream: https://github.com/google/fonts (v2.109), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-noto-kufi-arabic`.
 */
export declare const notoKufiArabic: PersianFont
