// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Vazirmatn (وزیرمتن) — Vazirmatn with Persian (Farsi) digits, 9 static weights (100-900). Same as next-persian-fonts 1.0.x.
 *
 * Upstream: https://github.com/rastikerdar/vazirmatn (v33.003), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-vazirmatn`.
 */
export const vazirMatn = localFont({
  src: [
    { path: './Vazirmatn-FD-Thin.woff2', weight: '100', style: 'normal' },
    { path: './Vazirmatn-FD-ExtraLight.woff2', weight: '200', style: 'normal' },
    { path: './Vazirmatn-FD-Light.woff2', weight: '300', style: 'normal' },
    { path: './Vazirmatn-FD-Regular.woff2', weight: '400', style: 'normal' },
    { path: './Vazirmatn-FD-Medium.woff2', weight: '500', style: 'normal' },
    { path: './Vazirmatn-FD-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: './Vazirmatn-FD-Bold.woff2', weight: '700', style: 'normal' },
    { path: './Vazirmatn-FD-ExtraBold.woff2', weight: '800', style: 'normal' },
    { path: './Vazirmatn-FD-Black.woff2', weight: '900', style: 'normal' },
  ],
  variable: '--font-vazirmatn',
  display: 'swap',
})

/** Alias of `vazirMatn`. */
export { vazirMatn as vazirmatnFD }
