// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Lalezar (لاله‌زار) — Lalezar display font, single weight (400).
 *
 * Upstream: https://github.com/google/fonts (v1.004), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-lalezar`.
 */
export const lalezar = localFont({
  src: [
    { path: './Lalezar-Regular.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-lalezar',
  display: 'swap',
})
