// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Lalezar (لاله‌زار) — Lalezar display font, single weight (400).
 *
 * Upstream: https://github.com/google/fonts (v1.004), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-lalezar`.
 */
export declare const lalezar: PersianFont
