// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Mirza (میرزا) — Mirza, 4 static weights (400, 500, 600, 700).
 *
 * Upstream: https://github.com/google/fonts (v1.0010g), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-mirza`.
 * Not preloaded (4 files); fonts load when first used. A variable export of the family preloads a single file.
 */
export const mirza = localFont({
  src: [
    { path: './Mirza-Regular.woff2', weight: '400', style: 'normal' },
    { path: './Mirza-Medium.woff2', weight: '500', style: 'normal' },
    { path: './Mirza-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: './Mirza-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-mirza',
  display: 'swap',
  preload: false,
})
