// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Nika (نیکا) — Nika display font, single weight (400). Arabic-script only (no Latin letters or Latin digits): pair it with a Latin font.
 *
 * Upstream: https://github.com/font-store/NikaFont (v1.0.0), license: OFL-1.1.
 * CSS variable: `--font-nika`.
 */
export declare const nika: PersianFont
