// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Amiri (امیری) — Amiri Naskh font: regular and bold, upright and italic.
 *
 * Upstream: https://github.com/google/fonts (v1.002), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-amiri`.
 */
export const amiri = localFont({
  src: [
    { path: './Amiri-Regular.woff2', weight: '400', style: 'normal' },
    { path: './Amiri-Bold.woff2', weight: '700', style: 'normal' },
    { path: './Amiri-Italic.woff2', weight: '400', style: 'italic' },
    { path: './Amiri-BoldItalic.woff2', weight: '700', style: 'italic' },
  ],
  variable: '--font-amiri',
  display: 'swap',
})
