// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Amiri (امیری) — Amiri Naskh font: regular and bold, upright and italic.
 *
 * Upstream: https://github.com/google/fonts (v1.002), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-amiri`.
 */
export declare const amiri: PersianFont
