// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Katibeh (کتیبه) — Katibeh display font, single weight (400).
 *
 * Upstream: https://github.com/google/fonts (v1.0010g), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-katibeh`.
 */
export const katibeh = localFont({
  src: [
    { path: './Katibeh-Regular.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-katibeh',
  display: 'swap',
})
