// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Samim (صمیم) — Samim with Persian digits, 3 static weights (400, 500, 700).
 *
 * Upstream: https://github.com/rastikerdar/samim-font (v4.0.5), license: OFL-1.1 (Arabic glyphs) + Bitstream Vera / Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-samim-fd`.
 */
export declare const samimFD: PersianFont
