// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Reem Kufi (ریم کوفی) — Reem Kufi variable font (wght 400-700). Note: ۵ uses the Arabic-style form.
 *
 * Upstream: https://github.com/google/fonts (v2.000), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-reem-kufi`.
 */
export declare const reemKufi: PersianFont
