// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Reem Kufi (ریم کوفی) — Reem Kufi variable font (wght 400-700). Note: ۵ uses the Arabic-style form.
 *
 * Upstream: https://github.com/google/fonts (v2.000), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-reem-kufi`.
 */
export const reemKufi = localFont({
  src: [
    { path: './ReemKufi-VF.woff2', weight: '400 700', style: 'normal' },
  ],
  variable: '--font-reem-kufi',
  display: 'swap',
})
