// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Rubik (روبیک) — Rubik variable font (wght 300-900), upright and italic.
 *
 * Upstream: https://github.com/google/fonts (v2.300), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-rubik`.
 */
export const rubik = localFont({
  src: [
    { path: './Rubik-VF.woff2', weight: '300 900', style: 'normal' },
    { path: './Rubik-Italic-VF.woff2', weight: '300 900', style: 'italic' },
  ],
  variable: '--font-rubik',
  display: 'swap',
})
