#!/usr/bin/env node
// Generates the package entry points, type declarations, exports map and FONTS.md
// from src/next-persian-fonts/fonts.json (the single source of truth).
//
//   node scripts/generate-fonts.mjs          # write files
//   node scripts/generate-fonts.mjs --check  # fail if generated files are out of date
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkgDir = join(root, 'src', 'next-persian-fonts')
const manifest = JSON.parse(readFileSync(join(pkgDir, 'fonts.json'), 'utf8'))
const check = process.argv.includes('--check')
const HEADER = '// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.'

let stale = []
const write = (file, content) => {
  const prev = existsSync(file) ? readFileSync(file, 'utf8') : null
  if (prev === content) return
  if (check) return stale.push(file.replace(root + '/', ''))
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, content)
}

const weightLabel = (files) => {
  const ws = [...new Set(files.map((f) => f.weight))]
  const label = ws.length === 1 ? ws[0].replace(' ', '–') : ws.join(', ')
  return files.some((f) => f.style === 'italic') ? `${label} + italic` : label
}
const isVariable = (files) => files.some((f) => f.weight.includes(' '))
// Exports with many files (static families with several weights) are not preloaded: Next.js would
// otherwise preload every weight on every page even though most pages use one or two of them.
const MAX_PRELOAD_FILES = 3
const preloads = (x) => x.preload !== false && x.files.length <= MAX_PRELOAD_FILES
const digitsLabel = { latin: 'Latin (0-9)', persian: 'Persian (۰-۹)', none: 'no Latin glyphs' }

function fontCall(family, v) {
  const src = v.files
    .map((f) => `    { path: './${f.to}', weight: '${f.weight}', style: '${f.style ?? 'normal'}' },`)
    .join('\n')
  const opts = [`  src: [\n${src}\n  ],`, `  variable: '${v.cssVariable}',`, `  display: 'swap',`]
  if (!preloads(v)) opts.push('  preload: false,')
  return `export const ${v.export} = localFont({\n${opts.join('\n')}\n})`
}

function jsdoc(family, v, extraVersion) {
  const lines = [
    `${family.name} (${family.nameFa}) — ${v.description}`,
    '',
    `Upstream: https://github.com/${family.repo} (v${extraVersion ?? family.version}), license: ${family.license}.`,
    ...(family.googleFonts ? ['Also on Google Fonts; bundled here so it works offline / without access to Google.'] : []),
    `CSS variable: \`${v.cssVariable}\`.`,
    ...(!preloads(v) && !v.deprecated ? [`Not preloaded (${v.files.length} files); fonts load when first used. A variable export of the family preloads a single file.`] : []),
  ]
  if (v.deprecated) lines.push('', `@deprecated ${v.deprecated}`)
  return '/**\n' + lines.map((l) => (l ? ` * ${l}` : ' *')).join('\n') + '\n */'
}

const exportsMap = { '.': { types: './index.d.ts', default: './index.js' } }
const files = ['index.js', 'index.d.ts', 'types.d.ts', 'fonts.json', 'FONTS.md', 'LICENSE.md', 'README.md']
const legacy = []
const rows = []

for (const family of manifest.families) {
  for (const v of family.variants) {
    const dir = join(pkgDir, v.subpath)
    const all = [v, ...(v.extra ?? [])]
    for (const x of all)
      for (const f of x.files)
        if (!existsSync(join(dir, f.to))) throw new Error(`Missing font file ${v.subpath}/${f.to} (run npm run fonts:update)`)

    const js = [HEADER, "import localFont from 'next/font/local'", '']
    const dts = [HEADER, "import type { PersianFont } from '../types.js'", '']
    for (const x of all) {
      js.push(jsdoc(family, x, x.version), fontCall(family, x), '')
      dts.push(jsdoc(family, x, x.version), `export declare const ${x.export}: PersianFont`, '')
      rows.push({ family, v, x })
    }
    for (const a of v.aliases ?? []) {
      js.push(`/** Alias of \`${v.export}\`. */`, `export { ${v.export} as ${a} }`, '')
      dts.push(`/** Alias of \`${v.export}\`. */`, `export { ${v.export} as ${a} }`, '')
    }
    write(join(dir, 'index.js'), js.join('\n').trimEnd() + '\n')
    write(join(dir, 'index.d.ts'), dts.join('\n').trimEnd() + '\n')
    exportsMap[`./${v.subpath}`] = { types: `./${v.subpath}/index.d.ts`, default: `./${v.subpath}/index.js` }
    files.push(v.subpath)
    if (v.legacy) legacy.push(v.subpath)
  }
}
exportsMap['./fonts.json'] = './fonts.json'
exportsMap['./package.json'] = './package.json'

const barrelNote = [
  '// The root entry only re-exports the fonts that existed in next-persian-fonts 1.0.x',
  '// (sahel, vazirmatn, estedad) for backward compatibility. Every font imported',
  '// through this barrel ends up in your CSS, so prefer subpath imports such as',
  "// `import { samim } from 'next-persian-fonts/samim'`.",
]
write(join(pkgDir, 'index.js'), [HEADER, ...barrelNote, ...legacy.map((s) => `export * from './${s}/index.js'`)].join('\n') + '\n')
write(join(pkgDir, 'index.d.ts'), [HEADER, ...barrelNote, "export type { PersianFont } from './types.js'", ...legacy.map((s) => `export * from './${s}/index.js'`)].join('\n') + '\n')

// package.json exports / files
const pkgPath = join(pkgDir, 'package.json')
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
pkg.exports = exportsMap
pkg.files = files
write(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

// FONTS.md
const md = [
  '<!-- Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand. -->',
  '# Bundled fonts',
  '',
  'Fonts are redistributed from their upstream repositories; the "Changes" column lists any conversion or subsetting. Each font folder contains the upstream license file.',
  '',
  `Exports with more than ${MAX_PRELOAD_FILES} files are not preloaded (marked "no preload"): they still load when used, but Next.js does not preload every weight on every page.`,
  '',
  '| Font | Import | Export | Weights | Digits | Upstream version | License | Source | Changes |',
  '|---|---|---|---|---|---|---|---|---|',
  ...rows.map(({ family, v, x }) => {
    const ver = x.version ?? family.version
    const name = `${family.name} (${family.nameFa})${x.deprecated ? ' — deprecated' : ''}`
    const w = `${weightLabel(x.files)}${isVariable(x.files) ? ' (variable)' : ''}${preloads(x) ? '' : ', no preload'}`
    const lic = `[${family.license}](./${v.subpath}/${family.licenseFile.to})`
    const src = family.repo === 'google/fonts' ? `[google/fonts](https://github.com/google/fonts/tree/main/ofl/${family.googleFontsDir})` : `[${family.repo}](https://github.com/${family.repo})`
    const changes = family.modification ? family.modification.replace(/\|/g, '/') : 'None (upstream WOFF2)'
    return `| ${name}${family.googleFonts ? ' ⓖ' : ''} | \`next-persian-fonts/${v.subpath}\` | \`${x.export}\` | ${w} | ${digitsLabel[x.digits]} | ${ver} | ${lic} | ${src} | ${changes} |`
  }),
  '',
  'Aliases: `vazirmatnFD` is an alias of `vazirMatn`.',
  '',
  'ⓖ = also available on Google Fonts. These are bundled so they work when Google is unreachable (e.g. during internet shutdowns in Iran) and builds never need to download fonts. Fonts whose license reserves their name (IBM Plex, SIL fonts) are shipped as the authors\' unmodified WOFF2 files; the others were converted to WOFF2 and subset to Arabic + Latin characters, which the OFL allows because no Reserved Font Name applies.',
  '',
]
write(join(pkgDir, 'FONTS.md'), md.join('\n'))

// Demo-only copies of every font with preload: false, so the gallery page does not preload ~90 files.
// The site and code fonts are imported from the package itself (and preloaded) and left out here: a second
// @font-face with the same family name would make the browser download their files twice.
const SITE_FONTS = new Set(['vazirmatnVariable', 'vazirCode'])
const gallery = [
  HEADER,
  '// Demo gallery only: the same font files as the package, but never preloaded.',
  "import localFont from 'next/font/local'",
  '',
  ...rows.filter(({ x }) => !SITE_FONTS.has(x.export)).map(({ v, x }) => {
    const src = x.files.map((f) => `    { path: '../next-persian-fonts/${v.subpath}/${f.to}', weight: '${f.weight}', style: '${f.style ?? 'normal'}' },`).join('\n')
    return `export const ${x.export} = localFont({\n  src: [\n${src}\n  ],\n  display: 'swap',\n  preload: false,\n})\n`
  }),
]
write(join(root, 'src', 'lib', 'gallery-fonts.generated.ts'), gallery.join('\n').trimEnd() + '\n')

if (check && stale.length) {
  console.error('Generated files are out of date:\n  ' + stale.join('\n  ') + '\nRun: npm run fonts:generate')
  process.exit(1)
}
console.log(check ? 'Generated files are up to date.' : `Generated ${rows.length} font exports in ${Object.keys(exportsMap).length - 3} subpaths.`)
