// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * El Messiri (المسیری) — El Messiri variable font (wght 400-700).
 *
 * Upstream: https://github.com/google/fonts (v2.020), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-el-messiri`.
 */
export const elMessiri = localFont({
  src: [
    { path: './ElMessiri[wght].woff2', weight: '400 700', style: 'normal' },
  ],
  variable: '--font-el-messiri',
  display: 'swap',
})
