// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * IBM Plex Sans Arabic (آی‌بی‌ام پلکس عربی) — IBM Plex Sans Arabic, 7 static weights (100-700).
 *
 * Upstream: https://github.com/IBM/plex (v1.1.0), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-ibm-plex-sans-arabic`.
 */
export const ibmPlexSansArabic = localFont({
  src: [
    { path: './IBMPlexSansArabic-Thin.woff2', weight: '100', style: 'normal' },
    { path: './IBMPlexSansArabic-ExtraLight.woff2', weight: '200', style: 'normal' },
    { path: './IBMPlexSansArabic-Light.woff2', weight: '300', style: 'normal' },
    { path: './IBMPlexSansArabic-Regular.woff2', weight: '400', style: 'normal' },
    { path: './IBMPlexSansArabic-Medium.woff2', weight: '500', style: 'normal' },
    { path: './IBMPlexSansArabic-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: './IBMPlexSansArabic-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-ibm-plex-sans-arabic',
  display: 'swap',
})
