// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * IBM Plex Sans Arabic (آی‌بی‌ام پلکس عربی) — IBM Plex Sans Arabic, 7 static weights (100-700).
 *
 * Upstream: https://github.com/IBM/plex (v1.1.0), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-ibm-plex-sans-arabic`.
 */
export declare const ibmPlexSansArabic: PersianFont
