// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Tanha (تنها) — Tanha with Persian digits, single weight (400).
 *
 * Upstream: https://github.com/rastikerdar/tanha-font (v0.10), license: Bitstream Vera License + Public Domain (changes) + Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-tanha-fd`.
 */
export const tanhaFD = localFont({
  src: [
    { path: './Tanha-FD.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-tanha-fd',
  display: 'swap',
})
