// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Tanha (تنها) — Tanha with Persian digits, single weight (400).
 *
 * Upstream: https://github.com/rastikerdar/tanha-font (v0.10), license: Bitstream Vera License + Public Domain (changes) + Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-tanha-fd`.
 */
export declare const tanhaFD: PersianFont
