// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Sahel (ساحل) — Sahel with Persian digits, 5 static weights.
 *
 * Upstream: https://github.com/rastikerdar/sahel-font (v3.4.0), license: OFL-1.1.
 * CSS variable: `--font-sahel-fd`.
 */
export const sahelFD = localFont({
  src: [
    { path: './Sahel-Light-FD.woff2', weight: '300', style: 'normal' },
    { path: './Sahel-FD.woff2', weight: '400', style: 'normal' },
    { path: './Sahel-SemiBold-FD.woff2', weight: '600', style: 'normal' },
    { path: './Sahel-Bold-FD.woff2', weight: '700', style: 'normal' },
    { path: './Sahel-Black-FD.woff2', weight: '900', style: 'normal' },
  ],
  variable: '--font-sahel-fd',
  display: 'swap',
})
