// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Sahel (ساحل) — Sahel with Persian digits, 5 static weights.
 *
 * Upstream: https://github.com/rastikerdar/sahel-font (v3.4.0), license: OFL-1.1.
 * CSS variable: `--font-sahel-fd`.
 */
export declare const sahelFD: PersianFont
