// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Tanha (تنها) — Tanha, single weight (400), Latin digits.
 *
 * Upstream: https://github.com/rastikerdar/tanha-font (v0.10), license: Bitstream Vera License + Public Domain (changes) + Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-tanha`.
 */
export const tanha = localFont({
  src: [
    { path: './Tanha.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-tanha',
  display: 'swap',
})
