// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Noto Naskh Arabic (نوتو نسخ) — Noto Naskh Arabic variable font (wght 400-700).
 *
 * Upstream: https://github.com/google/fonts (v2.021), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-noto-naskh-arabic`.
 */
export declare const notoNaskhArabic: PersianFont
