// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Vazir Code (وزیر کد) — Vazir Code monospace font with Persian digits, single weight (400).
 *
 * Upstream: https://github.com/rastikerdar/vazir-code-font (v1.1.2), license: Bitstream Vera License + Public Domain (changes).
 * CSS variable: `--font-vazir-code-fd`.
 */
export declare const vazirCodeFD: PersianFont
