// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Vazir Code (وزیر کد) — Vazir Code monospace font with Persian digits, single weight (400).
 *
 * Upstream: https://github.com/rastikerdar/vazir-code-font (v1.1.2), license: Bitstream Vera License + Public Domain (changes).
 * CSS variable: `--font-vazir-code-fd`.
 */
export const vazirCodeFD = localFont({
  src: [
    { path: './Vazir-Code-FD.woff2', weight: '400', style: 'normal' },
  ],
  variable: '--font-vazir-code-fd',
  display: 'swap',
})
