// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Shabnam (شبنم) — Shabnam with Persian digits, 5 static weights.
 *
 * Upstream: https://github.com/rastikerdar/shabnam-font (v5.0.1), license: OFL-1.1 (Arabic glyphs) + Bitstream Vera / Apache-2.0 (Latin glyphs).
 * CSS variable: `--font-shabnam-fd`.
 * Not preloaded (5 files); fonts load when first used. A variable export of the family preloads a single file.
 */
export const shabnamFD = localFont({
  src: [
    { path: './Shabnam-Thin-FD.woff2', weight: '100', style: 'normal' },
    { path: './Shabnam-Light-FD.woff2', weight: '300', style: 'normal' },
    { path: './Shabnam-FD.woff2', weight: '400', style: 'normal' },
    { path: './Shabnam-Medium-FD.woff2', weight: '500', style: 'normal' },
    { path: './Shabnam-Bold-FD.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-shabnam-fd',
  display: 'swap',
  preload: false,
})
