// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Changa (چنگا) — Changa variable font (wght 200-800).
 *
 * Upstream: https://github.com/google/fonts (v3.003), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-changa`.
 */
export const changa = localFont({
  src: [
    { path: './Changa-VF.woff2', weight: '200 800', style: 'normal' },
  ],
  variable: '--font-changa',
  display: 'swap',
})
