// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Changa (چنگا) — Changa variable font (wght 200-800).
 *
 * Upstream: https://github.com/google/fonts (v3.003), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-changa`.
 */
export declare const changa: PersianFont
