// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import localFont from 'next/font/local'

/**
 * Markazi Text (مرکزی) — Markazi Text variable font (wght 400-700).
 *
 * Upstream: https://github.com/google/fonts (v1.001), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-markazi-text`.
 */
export const markaziText = localFont({
  src: [
    { path: './MarkaziText[wght].woff2', weight: '400 700', style: 'normal' },
  ],
  variable: '--font-markazi-text',
  display: 'swap',
})
