// Generated by scripts/generate-fonts.mjs from fonts.json. Do not edit by hand.
import type { PersianFont } from '../types.js'

/**
 * Baloo Bhaijaan 2 (بالو بهایجان) — Baloo Bhaijaan 2 variable font (wght 400-800).
 *
 * Upstream: https://github.com/google/fonts (v1.701), license: OFL-1.1.
 * Also on Google Fonts; bundled here so it works offline / without access to Google.
 * CSS variable: `--font-baloo-bhaijaan-2`.
 */
export declare const balooBhaijaan2: PersianFont
